services:
    server:
        build:
            context: .
            target: dev
        ports:
            - 127.0.0.1:8080:8080
        volumes:
            - ./:/public:ro
        read_only: true
        cap_drop:
            - ALL
        security_opt:
            - no-new-privileges:true
