user nginx;
worker_processes auto;
pid /run/nginx.pid;
error_log /dev/stderr warn;
include /etc/nginx/modules/*.conf;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;
    access_log /dev/stdout;

    sendfile on;
    tcp_nopush on;
    keepalive_timeout 65;

    gzip_static on;
    brotli_static on;

    server {
        listen 80;
        server_name _;
        root /usr/share/nginx/html;
        index index.html;

        location ~ /\. {
            deny all;
            return 404;
        }

        location / {
            try_files $uri $uri/ =404;
        }
    }
}
